--CREATE DATABASE TaskTool
IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Project')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Project](
	[PrjID] [uniqueidentifier] NOT NULL,
	[ProjectID] [uniqueidentifier] NOT NULL,
	[Description] [Varchar](200),
	[ReleaseId] [uniqueidentifier] NOT NULL,
	[TeamId] [uniqueidentifier] NOT NULL
PRIMARY KEY CLUSTERED 
(
	[PrjID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO

IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Release')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Release](
	[ReleaseID] [uniqueidentifier] NOT NULL,	
	[Description] [Varchar](200)	
PRIMARY KEY CLUSTERED 
(
	[ReleaseID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO

IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Requirement')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Requirement](
	[ReqID] [uniqueidentifier] NOT NULL,	
	[PrjID] [uniqueidentifier] NOT NULL,
	[Description] [Varchar](200) NOT NULL	
PRIMARY KEY CLUSTERED 
(
	[ReqID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO	

IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Phase')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Phase](
	[PhaseID] [uniqueidentifier] NOT NULL,		
	[Description] [Varchar](200) NOT NULL	
PRIMARY KEY CLUSTERED 
(
	[PhaseID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO	

IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Activity')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Activity](
	[ActivityID] [uniqueidentifier] NOT NULL,	
	[PhaseID] [uniqueidentifier] NOT NULL,		
	[Description] [Varchar](200) NOT NULL	
PRIMARY KEY CLUSTERED 
(
	[ActivityID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO
	
IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Process')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Process](
	[ProcessID] [uniqueidentifier] NOT NULL,	
	[ActivityID] [uniqueidentifier] NOT NULL,		
	[Description] [Varchar](50) NOT NULL	
PRIMARY KEY CLUSTERED 
(
	[ProcessID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO		
 	
IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Team')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Team](
	[TeamID] [uniqueidentifier] NOT NULL,		
	[Name] [Varchar](50) NOT NULL	
PRIMARY KEY CLUSTERED 
(
	[TeamID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO

IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Employee')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Employee](
	[EmpID] [int] IDENTITY(1,1) NOT NULL,		
	[Name] [Varchar](50) NOT NULL,
	[TeamID] [uniqueidentifier] NOT NULL,	
PRIMARY KEY CLUSTERED 
(
	[EmpID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO	

IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Task')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Task](
	[TaskID] [uniqueidentifier] NOT NULL,		
	[Description] [Varchar](100) NOT NULL,
	[PrjID] [uniqueidentifier] NOT NULL,
	[ReqID] [uniqueidentifier] NOT NULL,
	[ProcessID] [uniqueidentifier] NOT NULL,
	[EmpID] [int] NOT NULL,
    [PlannedStartDate] [DateTime] NULL,
    [PlannedEndDate][DateTime] NULL,
	[ActualStartDate][DateTime] NULL,
	[ActualEndDate][DateTime] NULL,
	[CreatedDate][DateTime] NOT NULL,
	[UpdatedDate][DateTime] NOT NULL,
	[TotalDuration] [Decimal] NOT NULL,
	[TotalEffort] [Decimal] NOT NULL, 
	[TaskType] [Varchar](50),
    [Priority] [int] NOT NULL,
    [TaskStatus] [int] NOT NULL,
	[Allocation] [Varchar](50),
	[Comments] [Varchar] (100),
	[AnyChangeInReq] [bit],
	[Risk] [Varchar](50),
	[IsActive] [bit] NOT NULL DEFAULT 1,
PRIMARY KEY CLUSTERED 
(
	[TaskID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO

IF NOT EXISTS ( SELECT 1 FROM SYS.FOREIGN_KEYS WHERE name = 'fk_Project_ReleaseId') 
ALTER TABLE dbo.Project
ADD CONSTRAINT fk_Project_ReleaseId FOREIGN KEY(ReleaseId)REFERENCES dbo.Release(ReleaseId)
GO

IF NOT EXISTS ( SELECT 1 FROM SYS.FOREIGN_KEYS WHERE name = 'fk_Project_TeamId') 
ALTER TABLE dbo.Project
ADD CONSTRAINT fk_Project_TeamId FOREIGN KEY(TeamId)REFERENCES dbo.Team(TeamId)
GO

IF NOT EXISTS ( SELECT 1 FROM SYS.FOREIGN_KEYS WHERE name = 'fk_Requirement_PrjId')
ALTER TABLE dbo.Requirement
ADD CONSTRAINT fk_Requirement_PrjId FOREIGN KEY(PrjId)REFERENCES dbo.Project(PrjId)
GO

IF NOT EXISTS ( SELECT 1 FROM SYS.FOREIGN_KEYS WHERE name = 'fk_Activity_PhaseId')
ALTER TABLE dbo.Activity
ADD CONSTRAINT fk_Activity_PhaseId FOREIGN KEY(PhaseId)REFERENCES dbo.Phase(PhaseId)
GO

IF NOT EXISTS ( SELECT 1 FROM SYS.FOREIGN_KEYS WHERE name = 'fk_Process_ActivityId')
ALTER TABLE dbo.Process
ADD CONSTRAINT fk_Process_ActivityId FOREIGN KEY(ActivityId)REFERENCES dbo.Activity(ActivityId)
GO

IF NOT EXISTS ( SELECT 1 FROM SYS.FOREIGN_KEYS WHERE name = 'fk_Employee_TeamId')
ALTER TABLE dbo.Employee
ADD CONSTRAINT fk_Employee_TeamId FOREIGN KEY(TeamId)REFERENCES dbo.Team(TeamId)
GO

IF NOT EXISTS ( SELECT 1 FROM SYS.FOREIGN_KEYS WHERE name = 'fk_Task_PrjID')
ALTER TABLE dbo.Task
ADD CONSTRAINT fk_Task_PrjID FOREIGN KEY(PrjID)REFERENCES dbo.Project(PrjID)
GO

IF NOT EXISTS ( SELECT 1 FROM SYS.FOREIGN_KEYS WHERE name = 'fk_Task_ReqID')
ALTER TABLE dbo.Task
ADD CONSTRAINT fk_Task_ReqID FOREIGN KEY(ReqID)REFERENCES dbo.Requirement(ReqID)
GO

IF NOT EXISTS ( SELECT 1 FROM SYS.FOREIGN_KEYS WHERE name = 'fk_Task_ProcessID')
ALTER TABLE dbo.Task
ADD CONSTRAINT fk_Task_ProcessID FOREIGN KEY(ProcessID)REFERENCES dbo.Process(ProcessID)
GO

IF NOT EXISTS ( SELECT 1 FROM SYS.FOREIGN_KEYS WHERE name = 'fk_Task_EmpID')
ALTER TABLE dbo.Task
ADD CONSTRAINT fk_Task_EmpID FOREIGN KEY(EmpID)REFERENCES dbo.Employee(EmpID)
GO