IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Project')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Project](
	[PrjID] [int] IDENTITY(1,1) NOT NULL,
	[ProjectID] [int] NOT NULL,
	[Description] [Varchar](50),--Size to be increased bit more
	[ReleaseId] [int] NOT NULL,
	[TeamId] [int] NOT NULL
PRIMARY KEY CLUSTERED 
(
	[PrjID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO

IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Release')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Release](
	[ReleaseID] [int] IDENTITY(1,1) NOT NULL,	
	[Description] [Varchar](50)	
PRIMARY KEY CLUSTERED 
(
	[ReleaseID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO

IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Requirement')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Requirement](
	[ReqID] [int] IDENTITY(1,1) NOT NULL,	
	[PrjID] [int] NOT NULL,
	[Description] [Varchar](50) NOT NULL	
PRIMARY KEY CLUSTERED 
(
	[ReqID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO	

IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Phase')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Phase](
	[PhaseID] [int] IDENTITY(1,1) NOT NULL,		
	[Description] [Varchar](50) NOT NULL	
PRIMARY KEY CLUSTERED 
(
	[PhaseID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO	

IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Activity')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Activity](
	[ActivityID] [int] IDENTITY(1,1) NOT NULL,	
	[PhaseID] [int] NOT NULL,		
	[Description] [Varchar](50) NOT NULL	
PRIMARY KEY CLUSTERED 
(
	[ActivityID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO
	
IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Process')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Process](
	[ProcessID] [int] IDENTITY(1,1) NOT NULL,	
	[ActivityID] [int] NOT NULL,		
	[Description] [Varchar](50) NOT NULL	
PRIMARY KEY CLUSTERED 
(
	[ProcessID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO		
 	
IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Priority')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Priority](
	[PriorityID] [int] IDENTITY(1,1) NOT NULL,		
	[Description] [Varchar](50) NOT NULL	
PRIMARY KEY CLUSTERED 
(
	[PriorityID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO

IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Status')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Status](
	[StatusID] [int] IDENTITY(1,1) NOT NULL,		
	[Description] [Varchar](50) NOT NULL	
PRIMARY KEY CLUSTERED 
(
	[StatusID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO
	
IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Team')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Team](
	[TeamID] [int] IDENTITY(1,1) NOT NULL,		
	[Name] [Varchar](50) NOT NULL	
PRIMARY KEY CLUSTERED 
(
	[TeamID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO

IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Employee')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Employee](
	[EmpID] [int] IDENTITY(1,1) NOT NULL,		
	[Name] [Varchar](50) NOT NULL,
	[TeamID] [int] NOT NULL,		
PRIMARY KEY CLUSTERED 
(
	[EmpID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO	

IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE name='Task')
BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Task](
	[TaskID] [int] IDENTITY(1,1) NOT NULL,		
	[Description] [Varchar](100) NOT NULL,
	[PrjID] [int] NOT NULL,
	[ReqID] [int] NOT NULL,
	[ProcessID] [int] NOT NULL,
	[EmpID] [int] NOT NULL,
    [PlannedStartDate] [DateTime] NOT NULL,
    [PlannedEndDate][DateTime] NOT NULL,
	[ActualStartDate][DateTime] NOT NULL,
	[ActualEndDate][DateTime] NOT NULL,
	[CreatedDate][DateTime] NOT NULL,
	[UpdatedDate][DateTime] NOT NULL,
	[TotalDuration] [Decimal] NOT NULL,
	[TotalEffort] [Decimal] NOT NULL,
	[TaskType] [Varchar](50),
    [PriorityId] [int] NOT NULL,
    [TaskStatusId] [int] NOT NULL,
	[Allocation] [Varchar](50),
	[Comments] [Varchar] (100),
	[AnyChangeInReq] [bit],
	[Risk] [Varchar](50)
PRIMARY KEY CLUSTERED 
(
	[TaskID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO
