//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cognizant.Tools.ProjectMetrics.DataLayer.PM_EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Tasks = new HashSet<Tasks>();
        }
    
        public int EmpID { get; set; }
        public string Name { get; set; }
        public System.Guid TeamID { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}
