

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cognizant.Tools.ProjectMetrics.DataLayer.PM_EDMX
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class PMEntities : DbContext
{
    public PMEntities()
        : base("name=PMEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Activity> Activities { get; set; }

    public DbSet<Employee> Employees { get; set; }

    public DbSet<Phase> Phases { get; set; }

    public DbSet<Process> Processes { get; set; }

    public DbSet<Project> Projects { get; set; }

    public DbSet<Release> Releases { get; set; }

    public DbSet<Requirement> Requirements { get; set; }

    public DbSet<Team> Teams { get; set; }

    public DbSet<User> Users { get; set; }

    public DbSet<UserType> UserTypes { get; set; }

    public DbSet<ProjectTask> ProjectTasks { get; set; }

}

}

