//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cognizant.Tools.ProjectMetrics.DataLayer.PM_EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Requirements = new HashSet<Requirement>();
            this.Tasks = new HashSet<Task>();
        }
    
        public System.Guid PrjID { get; set; }
        public System.Guid ProjectID { get; set; }
        public string Description { get; set; }
        public System.Guid ReleaseId { get; set; }
        public System.Guid TeamId { get; set; }
    
        public virtual Release Release { get; set; }
        public virtual Team Team { get; set; }
        public virtual ICollection<Requirement> Requirements { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
