//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cognizant.Tools.ProjectMetrics.DataLayer.PM_EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        public Requirement()
        {
            this.Tasks = new HashSet<Tasks>();
        }
    
        public System.Guid ReqID { get; set; }
        public System.Guid PrjID { get; set; }
        public string Description { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}
