
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cognizant.Tools.ProjectMetrics.DataLayer.PM_EDMX
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public int ID { get; set; }

    public string Name { get; set; }

    public string Password { get; set; }

    public int UserTypeId { get; set; }



    public virtual UserType UserType { get; set; }

}

}
